# Generated by Django 3.2.23 on 2024-03-20 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20231201_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('root_project', 'root')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
