# Generated by Django 3.2.25 on 2024-04-22 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('projects_projectlist_get', 'ProjectListAPI_list your projects'), ('projects_projectlist_post', 'ProjectListAPI_create new projects'), ('projects_project_get', 'ProjectAPI_get project by id'), ('projects_project_patch', 'ProjectAPI_update project'), ('projects_project_put', 'ProjectAPI_unknow'), ('projects_project_del', 'ProjectAPI_delete project'), ('projects_project_post', 'ProjectAPI_unknow'), ('projects_projecttasklist_get', 'ProjectTaskListAPI_list project taks'), ('projects_projecttasklist_del', 'ProjectTaskListAPI_delete all taks'), ('projects_projecttasklist_post', 'ProjectTaskListAPI_unknow'), ('data_import_post', 'ImportAPI_import tasks'), ('data_export_get', 'ExportAPI_Easy export of tasks and annotations'), ('data_manager_action_get', 'ProjectActionsAPI_Get actions'), ('data_manager_action_post', 'ProjectActionsAPI_Post actions'), ('data_manager_view_get', 'ViewAPI_Get actions'), ('data_manager_view_post', 'ViewAPI_Post actions'), ('data_manager_view_patch', 'ViewAPI_Patch actions'), ('data_manager_view_put', 'ViewAPI_Put actions'), ('data_manager_view_super', 'ViewAPI_super'), ('ml_post', 'MLBackendDetailAPI_post ML'), ('ml_patch', 'MLBackendDetailAPI_patch ML'), ('ml_del', 'MLBackendDetailAPI_delete ML'), ('tasks_taskslist_get', 'TaskListAPI_get tasks list'), ('tasks_taskslist_post', 'TaskListAPI_create task'), ('tasks_get', 'TaskAPI_get task'), ('tasks_put', 'TaskAPI_unknow'), ('tasks_patch', 'TaskAPI_update task'), ('tasks_delete', 'TaskAPI_delete task'), ('tasks_annotationlist_get', 'AnnotationsListAPI_get alltask annotations'), ('tasks_annotationlist_post', 'AnnotationsListAPI_create annotation'), ('tasks_annotations_get', 'AnnotationAPI_get annotion by id'), ('tasks_annotations_put', 'AnnotationAPI_update annotion'), ('tasks_annotations_patch', 'AnnotationAPI_update annotion'), ('tasks_annotations_super', 'AnnotationAPI_super'), ('iostore_super', 'IOstore_super')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
