# Generated by Django 3.2.23 on 2024-03-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('projectlist_get', 'projects_view'), ('projectlist_post', 'projects_create'), ('project_get', 'projects_view'), ('project_del', 'projects_delete'), ('project_patch', 'projects_change'), ('project_put', 'projects_change'), ('project_post', 'projects_create'), ('projectimport_post', 'projects_import_create'), ('projectexport_get', 'projects_export_view'), ('dmaction_get', 'project_data_get'), ('dmaction_post', 'project_data_change'), ('dm_annotations_get', 'annotations_view'), ('dm_annotations_put', 'annotations_change'), ('dm_annotations_patch', 'annotations_change'), ('dm_annotations_del', 'annotations_delete')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
