# Generated by Django 3.2.23 on 2024-03-22 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('projectlist_get', 'projectslist_view'), ('projectlist_post', 'projectslist_create'), ('project_get', 'projects_view'), ('project_del', 'projects_delete'), ('project_patch', 'projects_change'), ('project_put', 'projects_change'), ('project_post', 'projects_create'), ('projectimport_post', 'projects_import_create'), ('projectexport_get', 'projects_export_view'), ('dmaction_get', 'project_data_get'), ('dmaction_post', 'project_data_change'), ('dm_annotations_get', 'annotations_view'), ('dm_annotations_post', 'annotations_submit'), ('dm_annotations_put', 'annotations_submit'), ('dm_annotations_patch', 'annotations_update'), ('dm_annotations_del', 'annotations_delete'), ('dm_labels_get', 'labels_view'), ('dm_labels_post', 'labels_submit'), ('dm_labels_put', 'labels_submit'), ('dm_labels_patch', 'labels_update'), ('dm_labels_del', 'labels_delete')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
