# Generated by Django 3.2.25 on 2024-03-29 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0045_auto_20231124_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='VIT_assurance_by',
            field=models.ForeignKey(help_text='Last user who assurance this annotation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assurance_annotations', to=settings.AUTH_USER_MODEL, verbose_name='assurance by'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='VIT_censor_by',
            field=models.ForeignKey(help_text='Last user who censor this annotation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='censor_annotations', to=settings.AUTH_USER_MODEL, verbose_name='censor by'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='VIT_is_assurance',
            field=models.BooleanField(default=False, verbose_name='is assurance'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='VIT_is_censored',
            field=models.BooleanField(default=False, verbose_name='is censored'),
        ),
    ]
