# Generated by Django 3.2.25 on 2024-04-17 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0048_auto_20240416_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='VIT_censor_by',
            new_name='VIT_censor_bypk',
        ),
    ]
