# Generated by Django 3.2.25 on 2024-04-17 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0049_rename_vit_censor_by_annotation_vit_censor_bypk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='VIT_censor_bypk',
        ),
    ]
